//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoDevSistemas2023Vini.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoDevSistemas2023Vini.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string _as {
            get {
                return ResourceManager.GetString("as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro Produto.
        /// </summary>
        internal static string botaoCadastroProduto_Text {
            get {
                return ResourceManager.GetString("botaoCadastroProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro Valor.
        /// </summary>
        internal static string botaoCadastroValor_Text {
            get {
                return ResourceManager.GetString("botaoCadastroValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clientes.
        /// </summary>
        internal static string botaoClientes_Text {
            get {
                return ResourceManager.GetString("botaoClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionário.
        /// </summary>
        internal static string botaoFuncionarios_Text {
            get {
                return ResourceManager.GetString("botaoFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes.
        /// </summary>
        internal static string botaoIngredientes_Text {
            get {
                return ResourceManager.GetString("botaoIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Principal.
        /// </summary>
        internal static string botaoPrincipal_Text {
            get {
                return ResourceManager.GetString("botaoPrincipal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sabores.
        /// </summary>
        internal static string botaoSabores_Text {
            get {
                return ResourceManager.GetString("botaoSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        internal static string buttonCancelar_Text {
            get {
                return ResourceManager.GetString("buttonCancelar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar.
        /// </summary>
        internal static string buttonLimpar_Text {
            get {
                return ResourceManager.GetString("buttonLimpar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string buttonSalvar_Text {
            get {
                return ResourceManager.GetString("buttonSalvar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select.
        /// </summary>
        internal static string buttonValidade_Text {
            get {
                return ResourceManager.GetString("buttonValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4 Queijos.
        /// </summary>
        internal static string checkBox4Queijos_Text {
            get {
                return ResourceManager.GetString("checkBox4Queijos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aplicar Agora!.
        /// </summary>
        internal static string checkBoxAplicar_Text {
            get {
                return ResourceManager.GetString("checkBoxAplicar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Calabresa.
        /// </summary>
        internal static string checkBoxCalabresa_Text {
            get {
                return ResourceManager.GetString("checkBoxCalabresa.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chocolate Branco.
        /// </summary>
        internal static string checkBoxChocolateBranco_Text {
            get {
                return ResourceManager.GetString("checkBoxChocolateBranco.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chocolate Preto.
        /// </summary>
        internal static string checkBoxChocolatePreto_Text {
            get {
                return ResourceManager.GetString("checkBoxChocolatePreto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Doritos.
        /// </summary>
        internal static string checkBoxDoritos_Text {
            get {
                return ResourceManager.GetString("checkBoxDoritos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filé com Palhas.
        /// </summary>
        internal static string checkBoxFilécomPalhas_Text {
            get {
                return ResourceManager.GetString("checkBoxFilécomPalhas.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maegherita.
        /// </summary>
        internal static string checkBoxMargherita_Text {
            get {
                return ResourceManager.GetString("checkBoxMargherita.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Portuguesa.
        /// </summary>
        internal static string checkBoxPortuguesa_Text {
            get {
                return ResourceManager.GetString("checkBoxPortuguesa.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria.
        /// </summary>
        internal static string comboBoxCategoria_Text {
            get {
                return ResourceManager.GetString("comboBoxCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/Regiao.
        /// </summary>
        internal static string comboBoxIdioma_Text {
            get {
                return ResourceManager.GetString("comboBoxIdioma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade bebida.
        /// </summary>
        internal static string comboBoxQtdBebida_Text {
            get {
                return ResourceManager.GetString("comboBoxQtdBebida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione.
        /// </summary>
        internal static string comboBoxTamanho_Text {
            get {
                return ResourceManager.GetString("comboBoxTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo Bebida.
        /// </summary>
        internal static string comboBoxTipoBebida_Text {
            get {
                return ResourceManager.GetString("comboBoxTipoBebida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja enviar para a bandeija? .
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma/região alterada com sucesso!.
        /// </summary>
        internal static string confirmidioma {
            get {
                return ResourceManager.GetString("confirmidioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados inseridos com sucesso!.
        /// </summary>
        internal static string dadosok {
            get {
                return ResourceManager.GetString("dadosok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgInicio {
            get {
                object obj = ResourceManager.GetObject("imgInicio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        internal static string labelBairro_Text1 {
            get {
                return ResourceManager.GetString("labelBairro.Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        internal static string labelBairroCliente_Text {
            get {
                return ResourceManager.GetString("labelBairroCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria.
        /// </summary>
        internal static string labelCategoriaPizza_Text {
            get {
                return ResourceManager.GetString("labelCategoriaPizza.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNH.
        /// </summary>
        internal static string labelCNH_Text {
            get {
                return ResourceManager.GetString("labelCNH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        internal static string labelComplementoCliente_Text {
            get {
                return ResourceManager.GetString("labelComplementoCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string labelCPF_Text {
            get {
                return ResourceManager.GetString("labelCPF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string labelCPFcliente_Text {
            get {
                return ResourceManager.GetString("labelCPFcliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço.
        /// </summary>
        internal static string labelEndereco_Text {
            get {
                return ResourceManager.GetString("labelEndereco.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço.
        /// </summary>
        internal static string labelEndereçoCliente_Text {
            get {
                return ResourceManager.GetString("labelEndereçoCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foto do Sabor.
        /// </summary>
        internal static string labelFotoDaPizza_Text {
            get {
                return ResourceManager.GetString("labelFotoDaPizza.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Função.
        /// </summary>
        internal static string labelFuncao_Text {
            get {
                return ResourceManager.GetString("labelFuncao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes.
        /// </summary>
        internal static string labelIDingredientes_Text {
            get {
                return ResourceManager.GetString("labelIDingredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID Pizza.
        /// </summary>
        internal static string labelIDpizza_Text {
            get {
                return ResourceManager.GetString("labelIDpizza.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ingredientes da Pizza.
        /// </summary>
        internal static string labelIngredientesPizza_Text {
            get {
                return ResourceManager.GetString("labelIngredientesPizza.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matricula.
        /// </summary>
        internal static string labelMatricula_Text {
            get {
                return ResourceManager.GetString("labelMatricula.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelNomeBebida_Text {
            get {
                return ResourceManager.GetString("labelNomeBebida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelNomeCliente_Text {
            get {
                return ResourceManager.GetString("labelNomeCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelNomeIngrediente_Text {
            get {
                return ResourceManager.GetString("labelNomeIngrediente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string labelNomePizza_Text {
            get {
                return ResourceManager.GetString("labelNomePizza.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero.
        /// </summary>
        internal static string labelNumCliente_Text {
            get {
                return ResourceManager.GetString("labelNumCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Outra.
        /// </summary>
        internal static string labelOutraBebida_Text {
            get {
                return ResourceManager.GetString("labelOutraBebida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua.
        /// </summary>
        internal static string labelRuaCliente_Text {
            get {
                return ResourceManager.GetString("labelRuaCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho.
        /// </summary>
        internal static string labelTamanhoBebida_Text {
            get {
                return ResourceManager.GetString("labelTamanhoBebida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho.
        /// </summary>
        internal static string labelTamanhoPizza_Text {
            get {
                return ResourceManager.GetString("labelTamanhoPizza.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string labelTel_Text {
            get {
                return ResourceManager.GetString("labelTel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string labelTelCliente_Text {
            get {
                return ResourceManager.GetString("labelTelCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo.
        /// </summary>
        internal static string labelTipobebida_Text {
            get {
                return ResourceManager.GetString("labelTipobebida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade.
        /// </summary>
        internal static string labelValidade_Text {
            get {
                return ResourceManager.GetString("labelValidade.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string labelValorBebida_Text {
            get {
                return ResourceManager.GetString("labelValorBebida.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor Borda.
        /// </summary>
        internal static string labelValorBorda_Text {
            get {
                return ResourceManager.GetString("labelValorBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        internal static string labelValorPizza_Text {
            get {
                return ResourceManager.GetString("labelValorPizza.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a R$.
        /// </summary>
        internal static string moeda {
            get {
                return ResourceManager.GetString("moeda", resourceCulture);
            }
        }
    }
}
